// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ExtractToPath(arg1:string,arg2:string,arg3:Array<string>):Promise<app.ExtractResult>;

export function GetSupportedFields():Promise<Array<app.FieldOption>>;

export function OpenFile(arg1:string):Promise<void>;

export function PreviewData(arg1:string,arg2:Array<string>):Promise<app.ExtractResult>;

export function SelectFile():Promise<string>;

export function SelectOutputPath(arg1:string):Promise<string>;
