// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractFromFile(arg1) {
  return window['go']['main']['App']['ExtractFromFile'](arg1);
}

export function PreviewData(arg1) {
  return window['go']['main']['App']['PreviewData'](arg1);
}

export function SaveToPath(arg1) {
  return window['go']['main']['App']['SaveToPath'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
