// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExtractToPath(arg1:string,arg2:string):Promise<main.ExtractResult>;

export function PreviewData(arg1:string):Promise<main.ExtractResult>;

export function SelectFile():Promise<string>;

export function SelectOutputPath(arg1:string):Promise<string>;
