// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {extractor} from '../models';

export function ExtractFromFile(arg1:string):Promise<main.ExtractResult>;

export function PreviewData(arg1:string):Promise<main.ExtractResult>;

export function SaveToPath(arg1:Array<extractor.Record>):Promise<main.ExtractResult>;

export function SelectFile():Promise<string>;
