// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractToPath(arg1, arg2) {
  return window['go']['main']['App']['ExtractToPath'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PreviewData(arg1) {
  return window['go']['main']['App']['PreviewData'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectOutputPath(arg1) {
  return window['go']['main']['App']['SelectOutputPath'](arg1);
}
